<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd\DowngradeRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>etcdserverpb.DowngradeRequest.DowngradeAction</code>
 */
class DowngradeAction
{
    /**
     * Generated from protobuf enum <code>VALIDATE = 0;</code>
     */
    const VALIDATE = 0;
    /**
     * Generated from protobuf enum <code>ENABLE = 1;</code>
     */
    const ENABLE = 1;
    /**
     * Generated from protobuf enum <code>CANCEL = 2;</code>
     */
    const CANCEL = 2;

    private static $valueToName = [
        self::VALIDATE => 'VALIDATE',
        self::ENABLE => 'ENABLE',
        self::CANCEL => 'CANCEL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

