<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd\AlarmRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>etcdserverpb.AlarmRequest.AlarmAction</code>
 */
class AlarmAction
{
    /**
     * Generated from protobuf enum <code>GET = 0;</code>
     */
    const GET = 0;
    /**
     * Generated from protobuf enum <code>ACTIVATE = 1;</code>
     */
    const ACTIVATE = 1;
    /**
     * Generated from protobuf enum <code>DEACTIVATE = 2;</code>
     */
    const DEACTIVATE = 2;

    private static $valueToName = [
        self::GET => 'GET',
        self::ACTIVATE => 'ACTIVATE',
        self::DEACTIVATE => 'DEACTIVATE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

