<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd\WatchCreateRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>etcdserverpb.WatchCreateRequest.FilterType</code>
 */
class FilterType
{
    /**
     * filter out put event.
     *
     * Generated from protobuf enum <code>NOPUT = 0;</code>
     */
    const NOPUT = 0;
    /**
     * filter out delete event.
     *
     * Generated from protobuf enum <code>NODELETE = 1;</code>
     */
    const NODELETE = 1;

    private static $valueToName = [
        self::NOPUT => 'NOPUT',
        self::NODELETE => 'NODELETE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

