<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/kv.proto

namespace Etcd\Event;

use UnexpectedValueException;

/**
 * Protobuf type <code>mvccpb.Event.EventType</code>
 */
class EventType
{
    /**
     * Generated from protobuf enum <code>PUT = 0;</code>
     */
    const PUT = 0;
    /**
     * Generated from protobuf enum <code>DELETE = 1;</code>
     */
    const DELETE = 1;

    private static $valueToName = [
        self::PUT => 'PUT',
        self::DELETE => 'DELETE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

