<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd\RangeRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>etcdserverpb.RangeRequest.SortTarget</code>
 */
class SortTarget
{
    /**
     * Generated from protobuf enum <code>KEY = 0;</code>
     */
    const KEY = 0;
    /**
     * Generated from protobuf enum <code>VERSION = 1;</code>
     */
    const VERSION = 1;
    /**
     * Generated from protobuf enum <code>CREATE = 2;</code>
     */
    const CREATE = 2;
    /**
     * Generated from protobuf enum <code>MOD = 3;</code>
     */
    const MOD = 3;
    /**
     * Generated from protobuf enum <code>VALUE = 4;</code>
     */
    const VALUE = 4;

    private static $valueToName = [
        self::KEY => 'KEY',
        self::VERSION => 'VERSION',
        self::CREATE => 'CREATE',
        self::MOD => 'MOD',
        self::VALUE => 'VALUE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

