<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd\RangeRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>etcdserverpb.RangeRequest.SortOrder</code>
 */
class SortOrder
{
    /**
     * default, no sorting
     *
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * lowest target value first
     *
     * Generated from protobuf enum <code>ASCEND = 1;</code>
     */
    const ASCEND = 1;
    /**
     * highest target value first
     *
     * Generated from protobuf enum <code>DESCEND = 2;</code>
     */
    const DESCEND = 2;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::ASCEND => 'ASCEND',
        self::DESCEND => 'DESCEND',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

