<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd\Compare;

use UnexpectedValueException;

/**
 * Protobuf type <code>etcdserverpb.Compare.CompareResult</code>
 */
class CompareResult
{
    /**
     * Generated from protobuf enum <code>EQUAL = 0;</code>
     */
    const EQUAL = 0;
    /**
     * Generated from protobuf enum <code>GREATER = 1;</code>
     */
    const GREATER = 1;
    /**
     * Generated from protobuf enum <code>LESS = 2;</code>
     */
    const LESS = 2;
    /**
     * Generated from protobuf enum <code>NOT_EQUAL = 3 [(.versionpb.etcd_version_enum_value) = "3.1"];</code>
     */
    const NOT_EQUAL = 3;

    private static $valueToName = [
        self::EQUAL => 'EQUAL',
        self::GREATER => 'GREATER',
        self::LESS => 'LESS',
        self::NOT_EQUAL => 'NOT_EQUAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

