<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.AlarmResponse</code>
 */
class AlarmResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * alarms is a list of alarms associated with the alarm request.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.AlarmMember alarms = 2;</code>
     */
    private $alarms;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *     @type \Etcd\AlarmMember[] $alarms
     *           alarms is a list of alarms associated with the alarm request.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * alarms is a list of alarms associated with the alarm request.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.AlarmMember alarms = 2;</code>
     * @return RepeatedField<\Etcd\AlarmMember>
     */
    public function getAlarms()
    {
        return $this->alarms;
    }

    /**
     * alarms is a list of alarms associated with the alarm request.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.AlarmMember alarms = 2;</code>
     * @param \Etcd\AlarmMember[] $var
     * @return $this
     */
    public function setAlarms($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcd\AlarmMember::class);
        $this->alarms = $arr;

        return $this;
    }

}

