<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use UnexpectedValueException;

/**
 * Protobuf type <code>etcdserverpb.AlarmType</code>
 */
class AlarmType
{
    /**
     * default, used to query if any alarm is active
     *
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * space quota is exhausted
     *
     * Generated from protobuf enum <code>NOSPACE = 1;</code>
     */
    const NOSPACE = 1;
    /**
     * kv store corruption detected
     *
     * Generated from protobuf enum <code>CORRUPT = 2 [(.versionpb.etcd_version_enum_value) = "3.3"];</code>
     */
    const CORRUPT = 2;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::NOSPACE => 'NOSPACE',
        self::CORRUPT => 'CORRUPT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

