<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.AlarmMember</code>
 */
class AlarmMember extends \Google\Protobuf\Internal\Message
{
    /**
     * memberID is the ID of the member associated with the raised alarm.
     *
     * Generated from protobuf field <code>uint64 memberID = 1;</code>
     */
    protected $memberID = 0;
    /**
     * alarm is the type of alarm which has been raised.
     *
     * Generated from protobuf field <code>.etcdserverpb.AlarmType alarm = 2;</code>
     */
    protected $alarm = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $memberID
     *           memberID is the ID of the member associated with the raised alarm.
     *     @type int $alarm
     *           alarm is the type of alarm which has been raised.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * memberID is the ID of the member associated with the raised alarm.
     *
     * Generated from protobuf field <code>uint64 memberID = 1;</code>
     * @return int|string
     */
    public function getMemberID()
    {
        return $this->memberID;
    }

    /**
     * memberID is the ID of the member associated with the raised alarm.
     *
     * Generated from protobuf field <code>uint64 memberID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemberID($var)
    {
        GPBUtil::checkUint64($var);
        $this->memberID = $var;

        return $this;
    }

    /**
     * alarm is the type of alarm which has been raised.
     *
     * Generated from protobuf field <code>.etcdserverpb.AlarmType alarm = 2;</code>
     * @return int
     */
    public function getAlarm()
    {
        return $this->alarm;
    }

    /**
     * alarm is the type of alarm which has been raised.
     *
     * Generated from protobuf field <code>.etcdserverpb.AlarmType alarm = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAlarm($var)
    {
        GPBUtil::checkEnum($var, \Etcd\AlarmType::class);
        $this->alarm = $var;

        return $this;
    }

}

