<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.AuthUserAddRequest</code>
 */
class AuthUserAddRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string password = 2;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>.authpb.UserAddOptions options = 3 [(.versionpb.etcd_version_field) = "3.4"];</code>
     */
    protected $options = null;
    /**
     * Generated from protobuf field <code>string hashedPassword = 4 [(.versionpb.etcd_version_field) = "3.5"];</code>
     */
    protected $hashedPassword = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $password
     *     @type \Etcd\UserAddOptions $options
     *     @type string $hashedPassword
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authpb.UserAddOptions options = 3 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @return \Etcd\UserAddOptions|null
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function hasOptions()
    {
        return isset($this->options);
    }

    public function clearOptions()
    {
        unset($this->options);
    }

    /**
     * Generated from protobuf field <code>.authpb.UserAddOptions options = 3 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @param \Etcd\UserAddOptions $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Etcd\UserAddOptions::class);
        $this->options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hashedPassword = 4 [(.versionpb.etcd_version_field) = "3.5"];</code>
     * @return string
     */
    public function getHashedPassword()
    {
        return $this->hashedPassword;
    }

    /**
     * Generated from protobuf field <code>string hashedPassword = 4 [(.versionpb.etcd_version_field) = "3.5"];</code>
     * @param string $var
     * @return $this
     */
    public function setHashedPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->hashedPassword = $var;

        return $this;
    }

}

