<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.AuthUserChangePasswordRequest</code>
 */
class AuthUserChangePasswordRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * name is the name of the user whose password is being changed.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * password is the new password for the user. Note that this field will be removed in the API layer.
     *
     * Generated from protobuf field <code>string password = 2;</code>
     */
    protected $password = '';
    /**
     * hashedPassword is the new password for the user. Note that this field will be initialized in the API layer.
     *
     * Generated from protobuf field <code>string hashedPassword = 3 [(.versionpb.etcd_version_field) = "3.5"];</code>
     */
    protected $hashedPassword = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           name is the name of the user whose password is being changed.
     *     @type string $password
     *           password is the new password for the user. Note that this field will be removed in the API layer.
     *     @type string $hashedPassword
     *           hashedPassword is the new password for the user. Note that this field will be initialized in the API layer.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * name is the name of the user whose password is being changed.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * name is the name of the user whose password is being changed.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * password is the new password for the user. Note that this field will be removed in the API layer.
     *
     * Generated from protobuf field <code>string password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * password is the new password for the user. Note that this field will be removed in the API layer.
     *
     * Generated from protobuf field <code>string password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * hashedPassword is the new password for the user. Note that this field will be initialized in the API layer.
     *
     * Generated from protobuf field <code>string hashedPassword = 3 [(.versionpb.etcd_version_field) = "3.5"];</code>
     * @return string
     */
    public function getHashedPassword()
    {
        return $this->hashedPassword;
    }

    /**
     * hashedPassword is the new password for the user. Note that this field will be initialized in the API layer.
     *
     * Generated from protobuf field <code>string hashedPassword = 3 [(.versionpb.etcd_version_field) = "3.5"];</code>
     * @param string $var
     * @return $this
     */
    public function setHashedPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->hashedPassword = $var;

        return $this;
    }

}

