<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.DeleteRangeResponse</code>
 */
class DeleteRangeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * deleted is the number of keys deleted by the delete range request.
     *
     * Generated from protobuf field <code>int64 deleted = 2;</code>
     */
    protected $deleted = 0;
    /**
     * if prev_kv is set in the request, the previous key-value pairs will be returned.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue prev_kvs = 3 [(.versionpb.etcd_version_field) = "3.1"];</code>
     */
    private $prev_kvs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *     @type int|string $deleted
     *           deleted is the number of keys deleted by the delete range request.
     *     @type \Etcd\KeyValue[] $prev_kvs
     *           if prev_kv is set in the request, the previous key-value pairs will be returned.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * deleted is the number of keys deleted by the delete range request.
     *
     * Generated from protobuf field <code>int64 deleted = 2;</code>
     * @return int|string
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * deleted is the number of keys deleted by the delete range request.
     *
     * Generated from protobuf field <code>int64 deleted = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeleted($var)
    {
        GPBUtil::checkInt64($var);
        $this->deleted = $var;

        return $this;
    }

    /**
     * if prev_kv is set in the request, the previous key-value pairs will be returned.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue prev_kvs = 3 [(.versionpb.etcd_version_field) = "3.1"];</code>
     * @return RepeatedField<\Etcd\KeyValue>
     */
    public function getPrevKvs()
    {
        return $this->prev_kvs;
    }

    /**
     * if prev_kv is set in the request, the previous key-value pairs will be returned.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue prev_kvs = 3 [(.versionpb.etcd_version_field) = "3.1"];</code>
     * @param \Etcd\KeyValue[] $var
     * @return $this
     */
    public function setPrevKvs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcd\KeyValue::class);
        $this->prev_kvs = $arr;

        return $this;
    }

}

