<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * DowngradeVersionTestRequest is used for test only. The version in
 * this request will be read as the WAL record version.If the downgrade
 * target version is less than this version, then the downgrade(online)
 * or migration(offline) isn't safe, so shouldn't be allowed.
 *
 * Generated from protobuf message <code>etcdserverpb.DowngradeVersionTestRequest</code>
 */
class DowngradeVersionTestRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ver = 1;</code>
     */
    protected $ver = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ver
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ver = 1;</code>
     * @return string
     */
    public function getVer()
    {
        return $this->ver;
    }

    /**
     * Generated from protobuf field <code>string ver = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVer($var)
    {
        GPBUtil::checkString($var, True);
        $this->ver = $var;

        return $this;
    }

}

