<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.DowngradeRequest</code>
 */
class DowngradeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * action is the kind of downgrade request to issue. The action may
     * VALIDATE the target version, DOWNGRADE the cluster version,
     * or CANCEL the current downgrading job.
     *
     * Generated from protobuf field <code>.etcdserverpb.DowngradeRequest.DowngradeAction action = 1;</code>
     */
    protected $action = 0;
    /**
     * version is the target version to downgrade.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     */
    protected $version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $action
     *           action is the kind of downgrade request to issue. The action may
     *           VALIDATE the target version, DOWNGRADE the cluster version,
     *           or CANCEL the current downgrading job.
     *     @type string $version
     *           version is the target version to downgrade.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * action is the kind of downgrade request to issue. The action may
     * VALIDATE the target version, DOWNGRADE the cluster version,
     * or CANCEL the current downgrading job.
     *
     * Generated from protobuf field <code>.etcdserverpb.DowngradeRequest.DowngradeAction action = 1;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * action is the kind of downgrade request to issue. The action may
     * VALIDATE the target version, DOWNGRADE the cluster version,
     * or CANCEL the current downgrading job.
     *
     * Generated from protobuf field <code>.etcdserverpb.DowngradeRequest.DowngradeAction action = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \Etcd\DowngradeRequest\DowngradeAction::class);
        $this->action = $var;

        return $this;
    }

    /**
     * version is the target version to downgrade.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * version is the target version to downgrade.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

}

