<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.DowngradeInfo</code>
 */
class DowngradeInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * enabled indicates whether the cluster is enabled to downgrade.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     */
    protected $enabled = false;
    /**
     * targetVersion is the target downgrade version.
     *
     * Generated from protobuf field <code>string targetVersion = 2;</code>
     */
    protected $targetVersion = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enabled
     *           enabled indicates whether the cluster is enabled to downgrade.
     *     @type string $targetVersion
     *           targetVersion is the target downgrade version.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * enabled indicates whether the cluster is enabled to downgrade.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * enabled indicates whether the cluster is enabled to downgrade.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * targetVersion is the target downgrade version.
     *
     * Generated from protobuf field <code>string targetVersion = 2;</code>
     * @return string
     */
    public function getTargetVersion()
    {
        return $this->targetVersion;
    }

    /**
     * targetVersion is the target downgrade version.
     *
     * Generated from protobuf field <code>string targetVersion = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->targetVersion = $var;

        return $this;
    }

}

