<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.HashKVResponse</code>
 */
class HashKVResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * hash is the hash value computed from the responding member's MVCC keys up to a given revision.
     *
     * Generated from protobuf field <code>uint32 hash = 2;</code>
     */
    protected $hash = 0;
    /**
     * compact_revision is the compacted revision of key-value store when hash begins.
     *
     * Generated from protobuf field <code>int64 compact_revision = 3;</code>
     */
    protected $compact_revision = 0;
    /**
     * hash_revision is the revision up to which the hash is calculated.
     *
     * Generated from protobuf field <code>int64 hash_revision = 4 [(.versionpb.etcd_version_field) = "3.6"];</code>
     */
    protected $hash_revision = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *     @type int $hash
     *           hash is the hash value computed from the responding member's MVCC keys up to a given revision.
     *     @type int|string $compact_revision
     *           compact_revision is the compacted revision of key-value store when hash begins.
     *     @type int|string $hash_revision
     *           hash_revision is the revision up to which the hash is calculated.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * hash is the hash value computed from the responding member's MVCC keys up to a given revision.
     *
     * Generated from protobuf field <code>uint32 hash = 2;</code>
     * @return int
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * hash is the hash value computed from the responding member's MVCC keys up to a given revision.
     *
     * Generated from protobuf field <code>uint32 hash = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkUint32($var);
        $this->hash = $var;

        return $this;
    }

    /**
     * compact_revision is the compacted revision of key-value store when hash begins.
     *
     * Generated from protobuf field <code>int64 compact_revision = 3;</code>
     * @return int|string
     */
    public function getCompactRevision()
    {
        return $this->compact_revision;
    }

    /**
     * compact_revision is the compacted revision of key-value store when hash begins.
     *
     * Generated from protobuf field <code>int64 compact_revision = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompactRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->compact_revision = $var;

        return $this;
    }

    /**
     * hash_revision is the revision up to which the hash is calculated.
     *
     * Generated from protobuf field <code>int64 hash_revision = 4 [(.versionpb.etcd_version_field) = "3.6"];</code>
     * @return int|string
     */
    public function getHashRevision()
    {
        return $this->hash_revision;
    }

    /**
     * hash_revision is the revision up to which the hash is calculated.
     *
     * Generated from protobuf field <code>int64 hash_revision = 4 [(.versionpb.etcd_version_field) = "3.6"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setHashRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->hash_revision = $var;

        return $this;
    }

}

