<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.HashKVRequest</code>
 */
class HashKVRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * revision is the key-value store revision for the hash operation.
     *
     * Generated from protobuf field <code>int64 revision = 1;</code>
     */
    protected $revision = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $revision
     *           revision is the key-value store revision for the hash operation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * revision is the key-value store revision for the hash operation.
     *
     * Generated from protobuf field <code>int64 revision = 1;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * revision is the key-value store revision for the hash operation.
     *
     * Generated from protobuf field <code>int64 revision = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->revision = $var;

        return $this;
    }

}

