<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.LeaseGrantRequest</code>
 */
class LeaseGrantRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * TTL is the advisory time-to-live in seconds. Expired lease will return -1.
     *
     * Generated from protobuf field <code>int64 TTL = 1;</code>
     */
    protected $TTL = 0;
    /**
     * ID is the requested ID for the lease. If ID is set to 0, the lessor chooses an ID.
     *
     * Generated from protobuf field <code>int64 ID = 2;</code>
     */
    protected $ID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $TTL
     *           TTL is the advisory time-to-live in seconds. Expired lease will return -1.
     *     @type int|string $ID
     *           ID is the requested ID for the lease. If ID is set to 0, the lessor chooses an ID.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * TTL is the advisory time-to-live in seconds. Expired lease will return -1.
     *
     * Generated from protobuf field <code>int64 TTL = 1;</code>
     * @return int|string
     */
    public function getTTL()
    {
        return $this->TTL;
    }

    /**
     * TTL is the advisory time-to-live in seconds. Expired lease will return -1.
     *
     * Generated from protobuf field <code>int64 TTL = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTTL($var)
    {
        GPBUtil::checkInt64($var);
        $this->TTL = $var;

        return $this;
    }

    /**
     * ID is the requested ID for the lease. If ID is set to 0, the lessor chooses an ID.
     *
     * Generated from protobuf field <code>int64 ID = 2;</code>
     * @return int|string
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * ID is the requested ID for the lease. If ID is set to 0, the lessor chooses an ID.
     *
     * Generated from protobuf field <code>int64 ID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkInt64($var);
        $this->ID = $var;

        return $this;
    }

}

