<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.LeaseCheckpointRequest</code>
 */
class LeaseCheckpointRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.LeaseCheckpoint checkpoints = 1;</code>
     */
    private $checkpoints;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\LeaseCheckpoint[] $checkpoints
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.LeaseCheckpoint checkpoints = 1;</code>
     * @return RepeatedField<\Etcd\LeaseCheckpoint>
     */
    public function getCheckpoints()
    {
        return $this->checkpoints;
    }

    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.LeaseCheckpoint checkpoints = 1;</code>
     * @param \Etcd\LeaseCheckpoint[] $var
     * @return $this
     */
    public function setCheckpoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcd\LeaseCheckpoint::class);
        $this->checkpoints = $arr;

        return $this;
    }

}

