<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.MemberAddRequest</code>
 */
class MemberAddRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * peerURLs is the list of URLs the added member will use to communicate with the cluster.
     *
     * Generated from protobuf field <code>repeated string peerURLs = 1;</code>
     */
    private $peerURLs;
    /**
     * isLearner indicates if the added member is raft learner.
     *
     * Generated from protobuf field <code>bool isLearner = 2 [(.versionpb.etcd_version_field) = "3.4"];</code>
     */
    protected $isLearner = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $peerURLs
     *           peerURLs is the list of URLs the added member will use to communicate with the cluster.
     *     @type bool $isLearner
     *           isLearner indicates if the added member is raft learner.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * peerURLs is the list of URLs the added member will use to communicate with the cluster.
     *
     * Generated from protobuf field <code>repeated string peerURLs = 1;</code>
     * @return RepeatedField<string>
     */
    public function getPeerURLs()
    {
        return $this->peerURLs;
    }

    /**
     * peerURLs is the list of URLs the added member will use to communicate with the cluster.
     *
     * Generated from protobuf field <code>repeated string peerURLs = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPeerURLs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->peerURLs = $arr;

        return $this;
    }

    /**
     * isLearner indicates if the added member is raft learner.
     *
     * Generated from protobuf field <code>bool isLearner = 2 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @return bool
     */
    public function getIsLearner()
    {
        return $this->isLearner;
    }

    /**
     * isLearner indicates if the added member is raft learner.
     *
     * Generated from protobuf field <code>bool isLearner = 2 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLearner($var)
    {
        GPBUtil::checkBool($var);
        $this->isLearner = $var;

        return $this;
    }

}

