<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.MemberAddResponse</code>
 */
class MemberAddResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * member is the member information for the added member.
     *
     * Generated from protobuf field <code>.etcdserverpb.Member member = 2;</code>
     */
    protected $member = null;
    /**
     * members is a list of all members after adding the new member.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.Member members = 3;</code>
     */
    private $members;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *     @type \Etcd\Member $member
     *           member is the member information for the added member.
     *     @type \Etcd\Member[] $members
     *           members is a list of all members after adding the new member.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * member is the member information for the added member.
     *
     * Generated from protobuf field <code>.etcdserverpb.Member member = 2;</code>
     * @return \Etcd\Member|null
     */
    public function getMember()
    {
        return $this->member;
    }

    public function hasMember()
    {
        return isset($this->member);
    }

    public function clearMember()
    {
        unset($this->member);
    }

    /**
     * member is the member information for the added member.
     *
     * Generated from protobuf field <code>.etcdserverpb.Member member = 2;</code>
     * @param \Etcd\Member $var
     * @return $this
     */
    public function setMember($var)
    {
        GPBUtil::checkMessage($var, \Etcd\Member::class);
        $this->member = $var;

        return $this;
    }

    /**
     * members is a list of all members after adding the new member.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.Member members = 3;</code>
     * @return RepeatedField<\Etcd\Member>
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * members is a list of all members after adding the new member.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.Member members = 3;</code>
     * @param \Etcd\Member[] $var
     * @return $this
     */
    public function setMembers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcd\Member::class);
        $this->members = $arr;

        return $this;
    }

}

