<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.MemberListRequest</code>
 */
class MemberListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool linearizable = 1 [(.versionpb.etcd_version_field) = "3.5"];</code>
     */
    protected $linearizable = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $linearizable
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool linearizable = 1 [(.versionpb.etcd_version_field) = "3.5"];</code>
     * @return bool
     */
    public function getLinearizable()
    {
        return $this->linearizable;
    }

    /**
     * Generated from protobuf field <code>bool linearizable = 1 [(.versionpb.etcd_version_field) = "3.5"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLinearizable($var)
    {
        GPBUtil::checkBool($var);
        $this->linearizable = $var;

        return $this;
    }

}

