<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.PutResponse</code>
 */
class PutResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * if prev_kv is set in the request, the previous key-value pair will be returned.
     *
     * Generated from protobuf field <code>.mvccpb.KeyValue prev_kv = 2 [(.versionpb.etcd_version_field) = "3.1"];</code>
     */
    protected $prev_kv = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *     @type \Etcd\KeyValue $prev_kv
     *           if prev_kv is set in the request, the previous key-value pair will be returned.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * if prev_kv is set in the request, the previous key-value pair will be returned.
     *
     * Generated from protobuf field <code>.mvccpb.KeyValue prev_kv = 2 [(.versionpb.etcd_version_field) = "3.1"];</code>
     * @return \Etcd\KeyValue|null
     */
    public function getPrevKv()
    {
        return $this->prev_kv;
    }

    public function hasPrevKv()
    {
        return isset($this->prev_kv);
    }

    public function clearPrevKv()
    {
        unset($this->prev_kv);
    }

    /**
     * if prev_kv is set in the request, the previous key-value pair will be returned.
     *
     * Generated from protobuf field <code>.mvccpb.KeyValue prev_kv = 2 [(.versionpb.etcd_version_field) = "3.1"];</code>
     * @param \Etcd\KeyValue $var
     * @return $this
     */
    public function setPrevKv($var)
    {
        GPBUtil::checkMessage($var, \Etcd\KeyValue::class);
        $this->prev_kv = $var;

        return $this;
    }

}

