<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.RangeResponse</code>
 */
class RangeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * kvs is the list of key-value pairs matched by the range request.
     * kvs is empty when count is requested.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue kvs = 2;</code>
     */
    private $kvs;
    /**
     * more indicates if there are more keys to return in the requested range.
     *
     * Generated from protobuf field <code>bool more = 3;</code>
     */
    protected $more = false;
    /**
     * count is set to the actual number of keys within the range when requested.
     * Unlike Kvs, it is unaffected by limits and filters (e.g., Min/Max, Create/Modify, Revisions)
     * and reflects the full count within the specified range.
     *
     * Generated from protobuf field <code>int64 count = 4;</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *     @type \Etcd\KeyValue[] $kvs
     *           kvs is the list of key-value pairs matched by the range request.
     *           kvs is empty when count is requested.
     *     @type bool $more
     *           more indicates if there are more keys to return in the requested range.
     *     @type int|string $count
     *           count is set to the actual number of keys within the range when requested.
     *           Unlike Kvs, it is unaffected by limits and filters (e.g., Min/Max, Create/Modify, Revisions)
     *           and reflects the full count within the specified range.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * kvs is the list of key-value pairs matched by the range request.
     * kvs is empty when count is requested.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue kvs = 2;</code>
     * @return RepeatedField<\Etcd\KeyValue>
     */
    public function getKvs()
    {
        return $this->kvs;
    }

    /**
     * kvs is the list of key-value pairs matched by the range request.
     * kvs is empty when count is requested.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue kvs = 2;</code>
     * @param \Etcd\KeyValue[] $var
     * @return $this
     */
    public function setKvs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcd\KeyValue::class);
        $this->kvs = $arr;

        return $this;
    }

    /**
     * more indicates if there are more keys to return in the requested range.
     *
     * Generated from protobuf field <code>bool more = 3;</code>
     * @return bool
     */
    public function getMore()
    {
        return $this->more;
    }

    /**
     * more indicates if there are more keys to return in the requested range.
     *
     * Generated from protobuf field <code>bool more = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setMore($var)
    {
        GPBUtil::checkBool($var);
        $this->more = $var;

        return $this;
    }

    /**
     * count is set to the actual number of keys within the range when requested.
     * Unlike Kvs, it is unaffected by limits and filters (e.g., Min/Max, Create/Modify, Revisions)
     * and reflects the full count within the specified range.
     *
     * Generated from protobuf field <code>int64 count = 4;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * count is set to the actual number of keys within the range when requested.
     * Unlike Kvs, it is unaffected by limits and filters (e.g., Min/Max, Create/Modify, Revisions)
     * and reflects the full count within the specified range.
     *
     * Generated from protobuf field <code>int64 count = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

}

