<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * RangeStreamResponse is the response for the RangeStream RPC.
 *
 * Generated from protobuf message <code>etcdserverpb.RangeStreamResponse</code>
 */
class RangeStreamResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * range_response is a partial response for the KV.RangeStream RPC.
     * The result of proto.Merge() applied on all responses should result in the
     * same RangeResponse response as to the Range() method.
     * Field population across chunks:
     *   - kvs: each chunk carries a disjoint slice of the result. Concatenating
     *     them in order yields the full key set.
     *   - header, more, count: set only on the final chunk. Non-merge clients
     *     can rely on io.EOF (end of stream) to detect completion. These
     *     fields are provided for clients that merge all responses into a
     *     single RangeResponse.
     *
     * Generated from protobuf field <code>.etcdserverpb.RangeResponse range_response = 1;</code>
     */
    protected $range_response = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\RangeResponse $range_response
     *           range_response is a partial response for the KV.RangeStream RPC.
     *           The result of proto.Merge() applied on all responses should result in the
     *           same RangeResponse response as to the Range() method.
     *           Field population across chunks:
     *             - kvs: each chunk carries a disjoint slice of the result. Concatenating
     *               them in order yields the full key set.
     *             - header, more, count: set only on the final chunk. Non-merge clients
     *               can rely on io.EOF (end of stream) to detect completion. These
     *               fields are provided for clients that merge all responses into a
     *               single RangeResponse.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * range_response is a partial response for the KV.RangeStream RPC.
     * The result of proto.Merge() applied on all responses should result in the
     * same RangeResponse response as to the Range() method.
     * Field population across chunks:
     *   - kvs: each chunk carries a disjoint slice of the result. Concatenating
     *     them in order yields the full key set.
     *   - header, more, count: set only on the final chunk. Non-merge clients
     *     can rely on io.EOF (end of stream) to detect completion. These
     *     fields are provided for clients that merge all responses into a
     *     single RangeResponse.
     *
     * Generated from protobuf field <code>.etcdserverpb.RangeResponse range_response = 1;</code>
     * @return \Etcd\RangeResponse|null
     */
    public function getRangeResponse()
    {
        return $this->range_response;
    }

    public function hasRangeResponse()
    {
        return isset($this->range_response);
    }

    public function clearRangeResponse()
    {
        unset($this->range_response);
    }

    /**
     * range_response is a partial response for the KV.RangeStream RPC.
     * The result of proto.Merge() applied on all responses should result in the
     * same RangeResponse response as to the Range() method.
     * Field population across chunks:
     *   - kvs: each chunk carries a disjoint slice of the result. Concatenating
     *     them in order yields the full key set.
     *   - header, more, count: set only on the final chunk. Non-merge clients
     *     can rely on io.EOF (end of stream) to detect completion. These
     *     fields are provided for clients that merge all responses into a
     *     single RangeResponse.
     *
     * Generated from protobuf field <code>.etcdserverpb.RangeResponse range_response = 1;</code>
     * @param \Etcd\RangeResponse $var
     * @return $this
     */
    public function setRangeResponse($var)
    {
        GPBUtil::checkMessage($var, \Etcd\RangeResponse::class);
        $this->range_response = $var;

        return $this;
    }

}

