<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.RequestOp</code>
 */
class RequestOp extends \Google\Protobuf\Internal\Message
{
    protected $request;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\RangeRequest $request_range
     *     @type \Etcd\PutRequest $request_put
     *     @type \Etcd\DeleteRangeRequest $request_delete_range
     *     @type \Etcd\TxnRequest $request_txn
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest request_range = 1;</code>
     * @return \Etcd\RangeRequest|null
     */
    public function getRequestRange()
    {
        return $this->readOneof(1);
    }

    public function hasRequestRange()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest request_range = 1;</code>
     * @param \Etcd\RangeRequest $var
     * @return $this
     */
    public function setRequestRange($var)
    {
        GPBUtil::checkMessage($var, \Etcd\RangeRequest::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.PutRequest request_put = 2;</code>
     * @return \Etcd\PutRequest|null
     */
    public function getRequestPut()
    {
        return $this->readOneof(2);
    }

    public function hasRequestPut()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.PutRequest request_put = 2;</code>
     * @param \Etcd\PutRequest $var
     * @return $this
     */
    public function setRequestPut($var)
    {
        GPBUtil::checkMessage($var, \Etcd\PutRequest::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.DeleteRangeRequest request_delete_range = 3;</code>
     * @return \Etcd\DeleteRangeRequest|null
     */
    public function getRequestDeleteRange()
    {
        return $this->readOneof(3);
    }

    public function hasRequestDeleteRange()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.DeleteRangeRequest request_delete_range = 3;</code>
     * @param \Etcd\DeleteRangeRequest $var
     * @return $this
     */
    public function setRequestDeleteRange($var)
    {
        GPBUtil::checkMessage($var, \Etcd\DeleteRangeRequest::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.TxnRequest request_txn = 4 [(.versionpb.etcd_version_field) = "3.3"];</code>
     * @return \Etcd\TxnRequest|null
     */
    public function getRequestTxn()
    {
        return $this->readOneof(4);
    }

    public function hasRequestTxn()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.TxnRequest request_txn = 4 [(.versionpb.etcd_version_field) = "3.3"];</code>
     * @param \Etcd\TxnRequest $var
     * @return $this
     */
    public function setRequestTxn($var)
    {
        GPBUtil::checkMessage($var, \Etcd\TxnRequest::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRequest()
    {
        return $this->whichOneof("request");
    }

}

