<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/auth.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Role is a single entry in the bucket authRoles
 *
 * Generated from protobuf message <code>authpb.Role</code>
 */
class Role extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .authpb.Permission keyPermission = 2;</code>
     */
    private $keyPermission;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \Etcd\Permission[] $keyPermission
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>bytes name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, False);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .authpb.Permission keyPermission = 2;</code>
     * @return RepeatedField<\Etcd\Permission>
     */
    public function getKeyPermission()
    {
        return $this->keyPermission;
    }

    /**
     * Generated from protobuf field <code>repeated .authpb.Permission keyPermission = 2;</code>
     * @param \Etcd\Permission[] $var
     * @return $this
     */
    public function setKeyPermission($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcd\Permission::class);
        $this->keyPermission = $arr;

        return $this;
    }

}

