<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.SnapshotResponse</code>
 */
class SnapshotResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * header has the current key-value store information. The first header in the snapshot
     * stream indicates the point in time of the snapshot.
     *
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * remaining_bytes is the number of blob bytes to be sent after this message
     *
     * Generated from protobuf field <code>uint64 remaining_bytes = 2;</code>
     */
    protected $remaining_bytes = 0;
    /**
     * blob contains the next chunk of the snapshot in the snapshot stream.
     *
     * Generated from protobuf field <code>bytes blob = 3;</code>
     */
    protected $blob = '';
    /**
     * local version of server that created the snapshot.
     * In cluster with binaries with different version, each cluster can return different result.
     * Informs which etcd server version should be used when restoring the snapshot.
     *
     * Generated from protobuf field <code>string version = 4 [(.versionpb.etcd_version_field) = "3.6"];</code>
     */
    protected $version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *           header has the current key-value store information. The first header in the snapshot
     *           stream indicates the point in time of the snapshot.
     *     @type int|string $remaining_bytes
     *           remaining_bytes is the number of blob bytes to be sent after this message
     *     @type string $blob
     *           blob contains the next chunk of the snapshot in the snapshot stream.
     *     @type string $version
     *           local version of server that created the snapshot.
     *           In cluster with binaries with different version, each cluster can return different result.
     *           Informs which etcd server version should be used when restoring the snapshot.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * header has the current key-value store information. The first header in the snapshot
     * stream indicates the point in time of the snapshot.
     *
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * header has the current key-value store information. The first header in the snapshot
     * stream indicates the point in time of the snapshot.
     *
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * remaining_bytes is the number of blob bytes to be sent after this message
     *
     * Generated from protobuf field <code>uint64 remaining_bytes = 2;</code>
     * @return int|string
     */
    public function getRemainingBytes()
    {
        return $this->remaining_bytes;
    }

    /**
     * remaining_bytes is the number of blob bytes to be sent after this message
     *
     * Generated from protobuf field <code>uint64 remaining_bytes = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRemainingBytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->remaining_bytes = $var;

        return $this;
    }

    /**
     * blob contains the next chunk of the snapshot in the snapshot stream.
     *
     * Generated from protobuf field <code>bytes blob = 3;</code>
     * @return string
     */
    public function getBlob()
    {
        return $this->blob;
    }

    /**
     * blob contains the next chunk of the snapshot in the snapshot stream.
     *
     * Generated from protobuf field <code>bytes blob = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBlob($var)
    {
        GPBUtil::checkString($var, False);
        $this->blob = $var;

        return $this;
    }

    /**
     * local version of server that created the snapshot.
     * In cluster with binaries with different version, each cluster can return different result.
     * Informs which etcd server version should be used when restoring the snapshot.
     *
     * Generated from protobuf field <code>string version = 4 [(.versionpb.etcd_version_field) = "3.6"];</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * local version of server that created the snapshot.
     * In cluster with binaries with different version, each cluster can return different result.
     * Informs which etcd server version should be used when restoring the snapshot.
     *
     * Generated from protobuf field <code>string version = 4 [(.versionpb.etcd_version_field) = "3.6"];</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

}

