<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.StatusResponse</code>
 */
class StatusResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * version is the cluster protocol version used by the responding member.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     */
    protected $version = '';
    /**
     * dbSize is the size of the backend database physically allocated, in bytes, of the responding member.
     *
     * Generated from protobuf field <code>int64 dbSize = 3;</code>
     */
    protected $dbSize = 0;
    /**
     * leader is the member ID which the responding member believes is the current leader.
     *
     * Generated from protobuf field <code>uint64 leader = 4;</code>
     */
    protected $leader = 0;
    /**
     * raftIndex is the current raft committed index of the responding member.
     *
     * Generated from protobuf field <code>uint64 raftIndex = 5;</code>
     */
    protected $raftIndex = 0;
    /**
     * raftTerm is the current raft term of the responding member.
     *
     * Generated from protobuf field <code>uint64 raftTerm = 6;</code>
     */
    protected $raftTerm = 0;
    /**
     * raftAppliedIndex is the current raft applied index of the responding member.
     *
     * Generated from protobuf field <code>uint64 raftAppliedIndex = 7 [(.versionpb.etcd_version_field) = "3.4"];</code>
     */
    protected $raftAppliedIndex = 0;
    /**
     * errors contains alarm/health information and status.
     *
     * Generated from protobuf field <code>repeated string errors = 8 [(.versionpb.etcd_version_field) = "3.4"];</code>
     */
    private $errors;
    /**
     * dbSizeInUse is the size of the backend database logically in use, in bytes, of the responding member.
     *
     * Generated from protobuf field <code>int64 dbSizeInUse = 9 [(.versionpb.etcd_version_field) = "3.4"];</code>
     */
    protected $dbSizeInUse = 0;
    /**
     * isLearner indicates if the member is raft learner.
     *
     * Generated from protobuf field <code>bool isLearner = 10 [(.versionpb.etcd_version_field) = "3.4"];</code>
     */
    protected $isLearner = false;
    /**
     * storageVersion is the version of the db file. It might be updated with delay in relationship to the target cluster version.
     *
     * Generated from protobuf field <code>string storageVersion = 11 [(.versionpb.etcd_version_field) = "3.6"];</code>
     */
    protected $storageVersion = '';
    /**
     * dbSizeQuota is the configured etcd storage quota in bytes (the value passed to etcd instance by flag --quota-backend-bytes)
     *
     * Generated from protobuf field <code>int64 dbSizeQuota = 12 [(.versionpb.etcd_version_field) = "3.6"];</code>
     */
    protected $dbSizeQuota = 0;
    /**
     * downgradeInfo indicates if there is downgrade process.
     *
     * Generated from protobuf field <code>.etcdserverpb.DowngradeInfo downgradeInfo = 13 [(.versionpb.etcd_version_field) = "3.6"];</code>
     */
    protected $downgradeInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *     @type string $version
     *           version is the cluster protocol version used by the responding member.
     *     @type int|string $dbSize
     *           dbSize is the size of the backend database physically allocated, in bytes, of the responding member.
     *     @type int|string $leader
     *           leader is the member ID which the responding member believes is the current leader.
     *     @type int|string $raftIndex
     *           raftIndex is the current raft committed index of the responding member.
     *     @type int|string $raftTerm
     *           raftTerm is the current raft term of the responding member.
     *     @type int|string $raftAppliedIndex
     *           raftAppliedIndex is the current raft applied index of the responding member.
     *     @type string[] $errors
     *           errors contains alarm/health information and status.
     *     @type int|string $dbSizeInUse
     *           dbSizeInUse is the size of the backend database logically in use, in bytes, of the responding member.
     *     @type bool $isLearner
     *           isLearner indicates if the member is raft learner.
     *     @type string $storageVersion
     *           storageVersion is the version of the db file. It might be updated with delay in relationship to the target cluster version.
     *     @type int|string $dbSizeQuota
     *           dbSizeQuota is the configured etcd storage quota in bytes (the value passed to etcd instance by flag --quota-backend-bytes)
     *     @type \Etcd\DowngradeInfo $downgradeInfo
     *           downgradeInfo indicates if there is downgrade process.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * version is the cluster protocol version used by the responding member.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * version is the cluster protocol version used by the responding member.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * dbSize is the size of the backend database physically allocated, in bytes, of the responding member.
     *
     * Generated from protobuf field <code>int64 dbSize = 3;</code>
     * @return int|string
     */
    public function getDbSize()
    {
        return $this->dbSize;
    }

    /**
     * dbSize is the size of the backend database physically allocated, in bytes, of the responding member.
     *
     * Generated from protobuf field <code>int64 dbSize = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDbSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->dbSize = $var;

        return $this;
    }

    /**
     * leader is the member ID which the responding member believes is the current leader.
     *
     * Generated from protobuf field <code>uint64 leader = 4;</code>
     * @return int|string
     */
    public function getLeader()
    {
        return $this->leader;
    }

    /**
     * leader is the member ID which the responding member believes is the current leader.
     *
     * Generated from protobuf field <code>uint64 leader = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLeader($var)
    {
        GPBUtil::checkUint64($var);
        $this->leader = $var;

        return $this;
    }

    /**
     * raftIndex is the current raft committed index of the responding member.
     *
     * Generated from protobuf field <code>uint64 raftIndex = 5;</code>
     * @return int|string
     */
    public function getRaftIndex()
    {
        return $this->raftIndex;
    }

    /**
     * raftIndex is the current raft committed index of the responding member.
     *
     * Generated from protobuf field <code>uint64 raftIndex = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRaftIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->raftIndex = $var;

        return $this;
    }

    /**
     * raftTerm is the current raft term of the responding member.
     *
     * Generated from protobuf field <code>uint64 raftTerm = 6;</code>
     * @return int|string
     */
    public function getRaftTerm()
    {
        return $this->raftTerm;
    }

    /**
     * raftTerm is the current raft term of the responding member.
     *
     * Generated from protobuf field <code>uint64 raftTerm = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRaftTerm($var)
    {
        GPBUtil::checkUint64($var);
        $this->raftTerm = $var;

        return $this;
    }

    /**
     * raftAppliedIndex is the current raft applied index of the responding member.
     *
     * Generated from protobuf field <code>uint64 raftAppliedIndex = 7 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @return int|string
     */
    public function getRaftAppliedIndex()
    {
        return $this->raftAppliedIndex;
    }

    /**
     * raftAppliedIndex is the current raft applied index of the responding member.
     *
     * Generated from protobuf field <code>uint64 raftAppliedIndex = 7 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setRaftAppliedIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->raftAppliedIndex = $var;

        return $this;
    }

    /**
     * errors contains alarm/health information and status.
     *
     * Generated from protobuf field <code>repeated string errors = 8 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @return RepeatedField<string>
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * errors contains alarm/health information and status.
     *
     * Generated from protobuf field <code>repeated string errors = 8 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->errors = $arr;

        return $this;
    }

    /**
     * dbSizeInUse is the size of the backend database logically in use, in bytes, of the responding member.
     *
     * Generated from protobuf field <code>int64 dbSizeInUse = 9 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @return int|string
     */
    public function getDbSizeInUse()
    {
        return $this->dbSizeInUse;
    }

    /**
     * dbSizeInUse is the size of the backend database logically in use, in bytes, of the responding member.
     *
     * Generated from protobuf field <code>int64 dbSizeInUse = 9 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setDbSizeInUse($var)
    {
        GPBUtil::checkInt64($var);
        $this->dbSizeInUse = $var;

        return $this;
    }

    /**
     * isLearner indicates if the member is raft learner.
     *
     * Generated from protobuf field <code>bool isLearner = 10 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @return bool
     */
    public function getIsLearner()
    {
        return $this->isLearner;
    }

    /**
     * isLearner indicates if the member is raft learner.
     *
     * Generated from protobuf field <code>bool isLearner = 10 [(.versionpb.etcd_version_field) = "3.4"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLearner($var)
    {
        GPBUtil::checkBool($var);
        $this->isLearner = $var;

        return $this;
    }

    /**
     * storageVersion is the version of the db file. It might be updated with delay in relationship to the target cluster version.
     *
     * Generated from protobuf field <code>string storageVersion = 11 [(.versionpb.etcd_version_field) = "3.6"];</code>
     * @return string
     */
    public function getStorageVersion()
    {
        return $this->storageVersion;
    }

    /**
     * storageVersion is the version of the db file. It might be updated with delay in relationship to the target cluster version.
     *
     * Generated from protobuf field <code>string storageVersion = 11 [(.versionpb.etcd_version_field) = "3.6"];</code>
     * @param string $var
     * @return $this
     */
    public function setStorageVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->storageVersion = $var;

        return $this;
    }

    /**
     * dbSizeQuota is the configured etcd storage quota in bytes (the value passed to etcd instance by flag --quota-backend-bytes)
     *
     * Generated from protobuf field <code>int64 dbSizeQuota = 12 [(.versionpb.etcd_version_field) = "3.6"];</code>
     * @return int|string
     */
    public function getDbSizeQuota()
    {
        return $this->dbSizeQuota;
    }

    /**
     * dbSizeQuota is the configured etcd storage quota in bytes (the value passed to etcd instance by flag --quota-backend-bytes)
     *
     * Generated from protobuf field <code>int64 dbSizeQuota = 12 [(.versionpb.etcd_version_field) = "3.6"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setDbSizeQuota($var)
    {
        GPBUtil::checkInt64($var);
        $this->dbSizeQuota = $var;

        return $this;
    }

    /**
     * downgradeInfo indicates if there is downgrade process.
     *
     * Generated from protobuf field <code>.etcdserverpb.DowngradeInfo downgradeInfo = 13 [(.versionpb.etcd_version_field) = "3.6"];</code>
     * @return \Etcd\DowngradeInfo|null
     */
    public function getDowngradeInfo()
    {
        return $this->downgradeInfo;
    }

    public function hasDowngradeInfo()
    {
        return isset($this->downgradeInfo);
    }

    public function clearDowngradeInfo()
    {
        unset($this->downgradeInfo);
    }

    /**
     * downgradeInfo indicates if there is downgrade process.
     *
     * Generated from protobuf field <code>.etcdserverpb.DowngradeInfo downgradeInfo = 13 [(.versionpb.etcd_version_field) = "3.6"];</code>
     * @param \Etcd\DowngradeInfo $var
     * @return $this
     */
    public function setDowngradeInfo($var)
    {
        GPBUtil::checkMessage($var, \Etcd\DowngradeInfo::class);
        $this->downgradeInfo = $var;

        return $this;
    }

}

