<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.TxnResponse</code>
 */
class TxnResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * succeeded is set to true if the compare evaluated to true or false otherwise.
     *
     * Generated from protobuf field <code>bool succeeded = 2;</code>
     */
    protected $succeeded = false;
    /**
     * responses is a list of responses corresponding to the results from applying
     * success if succeeded is true or failure if succeeded is false.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
     */
    private $responses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *     @type bool $succeeded
     *           succeeded is set to true if the compare evaluated to true or false otherwise.
     *     @type \Etcd\ResponseOp[] $responses
     *           responses is a list of responses corresponding to the results from applying
     *           success if succeeded is true or failure if succeeded is false.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * succeeded is set to true if the compare evaluated to true or false otherwise.
     *
     * Generated from protobuf field <code>bool succeeded = 2;</code>
     * @return bool
     */
    public function getSucceeded()
    {
        return $this->succeeded;
    }

    /**
     * succeeded is set to true if the compare evaluated to true or false otherwise.
     *
     * Generated from protobuf field <code>bool succeeded = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSucceeded($var)
    {
        GPBUtil::checkBool($var);
        $this->succeeded = $var;

        return $this;
    }

    /**
     * responses is a list of responses corresponding to the results from applying
     * success if succeeded is true or failure if succeeded is false.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
     * @return RepeatedField<\Etcd\ResponseOp>
     */
    public function getResponses()
    {
        return $this->responses;
    }

    /**
     * responses is a list of responses corresponding to the results from applying
     * success if succeeded is true or failure if succeeded is false.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
     * @param \Etcd\ResponseOp[] $var
     * @return $this
     */
    public function setResponses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcd\ResponseOp::class);
        $this->responses = $arr;

        return $this;
    }

}

