<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/auth.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>authpb.UserAddOptions</code>
 */
class UserAddOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool no_password = 1;</code>
     */
    protected $no_password = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $no_password
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool no_password = 1;</code>
     * @return bool
     */
    public function getNoPassword()
    {
        return $this->no_password;
    }

    /**
     * Generated from protobuf field <code>bool no_password = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoPassword($var)
    {
        GPBUtil::checkBool($var);
        $this->no_password = $var;

        return $this;
    }

}

