<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/auth.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * User is a single entry in the bucket authUsers
 *
 * Generated from protobuf message <code>authpb.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>bytes password = 2;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>repeated string roles = 3;</code>
     */
    private $roles;
    /**
     * Generated from protobuf field <code>.authpb.UserAddOptions options = 4;</code>
     */
    protected $options = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $password
     *     @type string[] $roles
     *     @type \Etcd\UserAddOptions $options
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>bytes name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, False);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>bytes password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, False);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string roles = 3;</code>
     * @return RepeatedField<string>
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * Generated from protobuf field <code>repeated string roles = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->roles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authpb.UserAddOptions options = 4;</code>
     * @return \Etcd\UserAddOptions|null
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function hasOptions()
    {
        return isset($this->options);
    }

    public function clearOptions()
    {
        unset($this->options);
    }

    /**
     * Generated from protobuf field <code>.authpb.UserAddOptions options = 4;</code>
     * @param \Etcd\UserAddOptions $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Etcd\UserAddOptions::class);
        $this->options = $var;

        return $this;
    }

}

