<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>etcdserverpb.WatchCancelRequest</code>
 */
class WatchCancelRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * watch_id is the watcher id to cancel so that no more events are transmitted.
     *
     * Generated from protobuf field <code>int64 watch_id = 1 [(.versionpb.etcd_version_field) = "3.1"];</code>
     */
    protected $watch_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $watch_id
     *           watch_id is the watcher id to cancel so that no more events are transmitted.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * watch_id is the watcher id to cancel so that no more events are transmitted.
     *
     * Generated from protobuf field <code>int64 watch_id = 1 [(.versionpb.etcd_version_field) = "3.1"];</code>
     * @return int|string
     */
    public function getWatchId()
    {
        return $this->watch_id;
    }

    /**
     * watch_id is the watcher id to cancel so that no more events are transmitted.
     *
     * Generated from protobuf field <code>int64 watch_id = 1 [(.versionpb.etcd_version_field) = "3.1"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setWatchId($var)
    {
        GPBUtil::checkInt64($var);
        $this->watch_id = $var;

        return $this;
    }

}

