<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/auth.proto

namespace GPBMetadata\Proto;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x98\x03\x0A\x10Proto/auth.proto\x12\x06authpb\"%\x0A\x0EUserAddOptions\x12\x13\x0A\x0Bno_password\x18\x01 \x01(\x08\"^\x0A\x04User\x12\x0C\x0A\x04name\x18\x01 \x01(\x0C\x12\x10\x0A\x08password\x18\x02 \x01(\x0C\x12\x0D\x0A\x05roles\x18\x03 \x03(\x09\x12'\x0A\x07options\x18\x04 \x01(\x0B2\x16.authpb.UserAddOptions\"\x83\x01\x0A\x0APermission\x12)\x0A\x08permType\x18\x01 \x01(\x0E2\x17.authpb.Permission.Type\x12\x0B\x0A\x03key\x18\x02 \x01(\x0C\x12\x11\x0A\x09range_end\x18\x03 \x01(\x0C\"*\x0A\x04Type\x12\x08\x0A\x04READ\x10\x00\x12\x09\x0A\x05WRITE\x10\x01\x12\x0D\x0A\x09READWRITE\x10\x02\"?\x0A\x04Role\x12\x0C\x0A\x04name\x18\x01 \x01(\x0C\x12)\x0A\x0DkeyPermission\x18\x02 \x03(\x0B2\x12.authpb.PermissionB&Z\x1Dgo.etcd.io/etcd/api/v3/authpb\xCA\x02\x04Etcdb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

