<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Proto/version.proto

namespace GPBMetadata\Proto;

class Version
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Au\x0A\x13Proto/version.proto\x12\x09versionpb\x1A google/protobuf/descriptor.protoB)Z go.etcd.io/etcd/api/v3/versionpb\xCA\x02\x04Etcdb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

